//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.ShowRooms = new HashSet<ShowRoom>();
        }
    
        public int Ci_ID { get; set; }
        public string CityName { get; set; }
    
        public virtual ICollection<ShowRoom> ShowRooms { get; set; }
    }
}
