//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Table
    {
        public int E_ID { get; set; }
        public string E_Name { get; set; }
        public string E_Address { get; set; }
        public string E_Desg { get; set; }
        public int E_Phone { get; set; }
        public decimal E_Salary { get; set; }
    }
}
