//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowRoom
    {
        public int S_ID { get; set; }
        public string ShowRName { get; set; }
        public int SRContectNumber { get; set; }
        public int City_ID { get; set; }
    
        public virtual City City { get; set; }
    }
}
