//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_Table
    {
        public Tax_Table()
        {
            this.RCB_Table = new HashSet<RCB_Table>();
        }
    
        public int T_ID { get; set; }
        public int T_Per { get; set; }
    
        public virtual ICollection<RCB_Table> RCB_Table { get; set; }
    }
}
